# Generated by Django 4.2.4 on 2023-09-22 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactno', models.CharField(max_length=10)),
                ('adhar', models.CharField(max_length=12)),
                ('adress', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=15)),
                ('place', models.CharField(max_length=15)),
                ('qualification', models.CharField(max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
    ]
